### ISSUE TITLE
Storybook 7 examples are failing with story code is not instrumented error

### ISSUE THREAD

**Issue by wfigueroa-chwy** [storybookjs/addon-coverage#25]
### Describe the bug

Both examples are failing when `test-storybook --coverage` is run.

### Steps to reproduce the behavior

1. Fresh repo clone and install all dependencies
2. Go to each example root
4. `yarn storybook` to start app
5. Run `yarn test-storybook --coverage` on separate terminal
6. See errors

### Expected behavior

Successful test coverage report should appear on terminal.

### Screenshots and/or logs

<img width="737" alt="image" src="https://github.com/storybookjs/addon-coverage/assets/64283444/5f6b9645-462a-4bdf-9894-5f8808775545">

### Environment

 - OS: macOS Ventura 13.5.2
 - Node.js version: v18.17.0
 - NPM version: v9.6.7

**Comment by Akash-M** [comment]
+1

**Comment by rmsnk** [comment]
+1

**Comment by s8n11c** [comment]
This addon mutates @storybook/addon-coverage coverage webpack presets by replacing babel-loader with swc loader that removes the configs set for coverage reporting, so when storybook starts it starts without setting up the coverage configs you need

in order to fix that you need to remove @storybook/addon-coverage and replace it with this
https://github.com/kwonoj/swc-plugin-coverage-instrument

**Comment by shajjhusein** [comment]
+1

**Comment by shajjhusein** [comment]
you need to install @storybook/jest

**Comment by dhbloskarv** [comment]
but @storybook/jest is installed

**Comment by shajjhusein** [comment]
A new version of Storybook (7.5.0) is now available. You should consider upgrading to address the issue.

**Comment by valentinpalkovic** [comment]
Fixed by https://github.com/storybookjs/addon-coverage/pull/27
